services:

  mongo-prod:
    image: mongo
    container_name: mongo-prod
    restart: unless-stopped
    ports:
      - ${MONGO_LOCAL_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ADMIN_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ADMIN_PASSWORD}
    networks:
      - prod-network
    volumes:
      - mogo-prod-data:/data/db
  
  biz-away:
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true
    container_name: bizAway-BE
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      mongo-prod:
        condition: service_started
    environment:
      - SERVER_PORT=3000
      - DATABASE_URL=mongodb://${MONGO_ADMIN_USER}:${MONGO_ADMIN_PASSWORD}@mongo-prod:27017/${MONGO_DB_NAME}?authSource=admin
    ports:
      - ${SERVER_PORT}:3000
    networks:
      - prod-network

networks:
  prod-network:

volumes:
  mogo-prod-data: