services:
  
  mongo-test:
    image: mongo
    container_name: mongo-test
    restart: unless-stopped
    ports:
      - ${MONGO_LOCAL_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ADMIN_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ADMIN_PASSWORD}
    networks:
      - test-network
  
  redis-test:
    image: redis/redis-stack-server
    container_name: redis-test
    restart: unless-stopped
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - test-network
  
networks:
  test-network:
  
    