services:

  mongo:
    image: mongo
    container_name: mongo-dev
    restart: unless-stopped
    ports:
      - ${MONGO_LOCAL_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ADMIN_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ADMIN_PASSWORD}
    networks:
      - dev-network
  
networks:
  dev-network: