services:

  mongo-prod:
    image: mongo
    container_name: mongo-prod
    restart: unless-stopped
    ports:
      - ${MONGO_LOCAL_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ADMIN_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ADMIN_PASSWORD}
    networks:
      - prod-network
  
networks:
  prod-network:

  # myApp: // here the code to build and start my app