services:

  mongo:
    image: mongo
    container_name: mongo-dev
    restart: unless-stopped
    ports:
      - ${MONGO_LOCAL_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ADMIN_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ADMIN_PASSWORD}
  
  mongo-express-dev:
    image: mongo-express
    restart: unless-stopped
    ports:
      - ${MONGO_WEB_CLIENT_LOCAL_PORT}:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ADMIN_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ADMIN_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ADMIN_USER}:${MONGO_ADMIN_PASSWORD}@mongo:27017/
      ME_CONFIG_BASICAUTH: false